services:
    mysql:
     image: mysql:latest
     environment:
       - MYSQL_ROOT_PASSWORD=root      
     ports:
      - "3306:3306"
    rabbitmq:
        image: rabbitmq:3.10-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=christian
            - RABBITMQ_DEFAULT_PASS=senha
#    rabbitmq-init:
#        image: rabbitmq:3.10-management
#        depends_on:
#            - rabbitmq
#        links: rabbitmq
#        command: rabbitmq-plugins enable rabbitmq_shovel rabbitmq_shovel_management
